### ISSUE TITLE
The elements of the batch contain different keys

### ISSUE THREAD

**Issue by Mutturaj-BEL** [LennyBijan/FinetuningWhisperWithMedium#1]
/home/maedelta/python38/python38/lib64/python3.8/site-packages/torch/cuda/__init__.py:619: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/maedelta/voice-to-text/pythonProject/FinetuningWhisperWithMedium/Pipeline_Transcribe_Parse.py", line 58, in <module>
    results = pipe(audios, batch_size=len(audios))
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 285, in __call__
    return super().__call__(inputs, **kwargs)
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/transformers/pipelines/base.py", line 1224, in __call__
    outputs = list(final_iterator)
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/transformers/pipelines/pt_utils.py", line 269, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 42, in fetch
    return self.collate_fn(data)
  File "/home/maedelta/python38/python38/lib64/python3.8/site-packages/transformers/pipelines/base.py", line 172, in inner
    raise ValueError(
ValueError: The elements of the batch contain different keys. Cannot batch them ({'segment_size', 'input_features', 'is_last'} != {'input_features', 'is_last'})

**Comment by Mutturaj-BEL** [comment]
Got above error in this line 
results = pipe(audios, batch_size=len(audios))

**Comment by LennyBijan** [comment]
I updated the script because there was an error in folder creation. I'm not sure that was the root of your issue though - here are a few things to check:

- did you use pipeline_cunk for the creation of the audio files? Its necessary you use that script if you wanna use the next one as it gives you the right file structure to work with. 
- are all your audio files in .wav format?
- is your base_directory and output_directory configured correctly?
- decrease the batch size in line 27
- is the metadata file in the correct .csv format? I've added an example file how the result should look like after this step
[metadata_test.csv](https://github.com/user-attachments/files/16784359/metadata_test.csv)

**Comment by Mutturaj-BEL** [comment]
Thank u for quick response.

1. I have used used the pipeline_cunk for the creation of the audio files.
2.  Yes, all your audio files in .wav format , details of audio file
Metadata:
    encoder         : Lavf58.29.100
  Duration: 02:11:19.81, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s16, 256 kb/s
   3.11 M-A:  0.000 fd=   0 aq=  106KB vq=    0KB sq=    0B f=0/0  
 
3.Yes my your base_directory and output_directory configured correctly.

4.decrease the batch size in line 27
I tried chunk size to 10. still same error

4.Yes metadata_test.csv is correct .

5.I have changed pipeline code to 
 results = pipe(batch_audio_paths.copy(), generate_kwargs={"language": "en", "task": "transcribe"})

With this change , there is no error &  metadata_test.csv has got the data in expected format.

**Comment by LennyBijan** [comment]
thank you for taking your time to figure out the issue! This probably stems from the fact that I used a german ASR model and didn't update the code for full customizability - I'd appreciate it if you could open a pull request with the documentation as other people will probably run into the same issues. 

Again thank you for working with my code and I hope you get the results you were trying to achieve!
